name = "RegularizationTools"
uuid = "29dad682-9a27-4bc3-9c72-016788665182"
authors = ["Markus Petters"]
version = "0.1.0"

[compat]
julia = "1.5.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
